#!/usr/bin/env bash
#Tree-building with Harvest Suite and Nextstrain
#Harvest Suite: Parsnp performs microbial core genome alignment and SNP detection; Harvest-tools converts the Parsnp output (.xmfa) to a format Augur can accept (.vcf)
#Nextstrain: Augur is the bioinformatics pipeline that builds the tree; Auspice is the interactive web-based visualizer

#Docker images required: Parsnp, Harvest-tools, Nextstrain
#Files required (see below for explanations): reference sequence (.fasta), a directory of sequences (.fasta) of the samples, metadata (.tsv), auspice-config-custom-data.json (custom settings for tree)
##Do not include the reference genome in the fasta directory or metadata file
##Metadata tsv should have the following column headers: strain, subspecies, country, date, source, type
##Dates must be in the format YYYY-MM-DD with unknown fields as X's, i.e. 2013-05-XX, 195X-XX-XX, or XXXX-XX-XX
##The contents of the "strain" column must exactly match the names of the fasta files (this is basically the sample name), including any file extension (either remove the ".fasta" from each consensus sequence file name or include ".fasta" in the strain name)
##The strain names cannot contain any spaces or special characters such as ()[]{}|#><

#Variables
reference_fasta="data/tularensis_SCHU_S4_reference.fasta"
samples_fasta_directory="data/fasta/"
samples_metadata="data/nextstrain_metadata.tsv" 
temp_file_directory="results/nextstrain_temp/"
output_directory="results/nextstrain_output/"

#Parsnp for alignment
parsnp -d $samples_fasta_directory -r $reference_fasta -o $temp_file_directory

#Harvest-tools for file conversion
harvesttools -x $temp_file_directory/parsnp.xmfa -V $temp_file_directory/alignment.vcf -f $reference_fasta

#Augur for tree-building
nextstrain shell .
augur tree --alignment $temp_file_directory/alignment.vcf --output $temp_file_directory/tree_raw.nwk --vcf-reference $reference_fasta
augur refine --tree $temp_file_directory/tree_raw.nwk --alignment $temp_file_directory/alignment.vcf --metadata $samples_metadata --output-tree $temp_file_directory/tree.nwk --output-node-data $temp_file_directory/branch_lengths.json --vcf-reference $reference_fasta --timetree --coalescent opt --stochastic-resolve 
augur export v2 --tree $temp_file_directory/tree.nwk --metadata $samples_metadata --node-data $temp_file_directory/branch_lengths.json --output $output_directory/final_tree.json --auspice-config auspice-config-custom-data.json
exit

#View tree
auspice view --datasetDir $output_directory
#Follow the link printed in the terminal
